Elektrobit/ebcl_template

- images/qemu-crinit-aarch64/root/etc/crinit/default.series
- images/qemu-crinit-amd64/root/etc/crinit/default.series
Remove not existing config option from the default.series. It does not exist and just causes warnings during boot.
> qemu-crinit: Remove invalid config options

- docs/images/params.md
- docs/tools/initrd.md
Update docs to reflect new handling of packages parameter.
Related to: https://github.com/Elektrobit/ebcl_build_tools/pull/9
> EBLINUX-26196: Update initrd-generator docs

- .devcontainer/devcontainer.json
- .env
- apps/meminfo-reader/CMakeLists.txt
- apps/my-json-app/CMakeLists.txt
Included GNUInstallDirs to fix install locations with CMAKE_INSTALL_<dir>
[fix cmake install prefix](https://github.com/Elektrobit/ebcl_dev_container/pull/16)
```bash
```
> added missing include for GNUInstallDirs

- init_workspace
After debugging with a colleague for a while,
we found out that the required packages were missing in the VM.
If the binfmt or qemu-static-user packages are missing, there error messages during image build are 
very misleading and do not help to solve the issue.
This change should save others some time.
none
```bash
```
> Quality of life: Ensure required tools are installed on host

- .devcontainer/devcontainer.json
- docs/examples/kernel.md
- docs/examples/rdb2.md
- docs/images/from_scatch.md
- images/amd64/appdev/qemu/crinit/config/etc/apt/sources.list
- images/amd64/appdev/qemu/crinit/config_root.sh
- images/amd64/qemu/ebcl-server/crinit/config/etc/apt/sources.list
- images/amd64/qemu/ebcl-server/crinit/config/etc/crinit/crinit.d/earlysetup.crinit
- images/amd64/qemu/ebcl/crinit/config_root.sh
- images/arm64/appdev/pi4/crinit/config_crinit.sh
- images/arm64/appdev/pi4/crinit/crinit_config/etc/apt/sources.list
- images/arm64/appdev/pi4/systemd/systemd_config/etc/apt/sources.list
- images/arm64/appdev/qemu/crinit/config/etc/apt/sources.list
- images/arm64/appdev/qemu/crinit/config_root.sh
- images/arm64/appdev/rdb2/base.yaml
- images/arm64/appdev/rdb2/crinit/config_root.sh
- images/arm64/appdev/rdb2/systemd/systemd_config/etc/apt/sources.list
- images/arm64/nxp/rdb2/base.yaml
- images/arm64/nxp/rdb2/boot_root.yaml
- images/arm64/nxp/rdb2/crinit/config_root.sh
- images/arm64/nxp/rdb2/crinit/crinit_config/etc/crinit/crinit.d/earlysetup.crinit
- images/arm64/nxp/rdb2/kernel_src/Makefile
- images/arm64/nxp/rdb2/network/config_root.sh
- images/arm64/nxp/rdb2/systemd/server/config/etc/apt/sources.list
- images/arm64/qemu/ebcl/crinit/config_root.sh
- images/arm64/raspberry/pi4/crinit/config_crinit.sh
- images/arm64/raspberry/pi4/crinit/crinit_config/etc/apt/sources.list
- images/arm64/raspberry/pi4/systemd/systemd_config/etc/apt/sources.list
- images/example-old-images/qemu/berrymill/berrymill.conf
- images/example-old-images/qemu/berrymill/root/etc/apt/sources.list
- Fix comments
- Fix exec rights of modprobe.sh and other scripts
- Fix hostnames
- Make use of new RDB2 kernel
none
```bash
(venv) ebcl@e33ca934e2f8:/workspace/robot_tests$ robot images.robot 
==============================================================================
Images                                                                        
==============================================================================
Build Image amd64/qemu/jammy                                          | PASS |
------------------------------------------------------------------------------
Build Image amd64/qemu/ebcl/systemd                                   | PASS |
------------------------------------------------------------------------------
Build Image amd64/qemu/ebcl/crinit …
```
> Fix review findings

- docs/intro/setup.md
- init_workspace
python is only required to run the tests, not for using the sdk
> drop python from host dependencies

- apps/meminfo-reader/CMakePresets.json
- apps/my-json-app/CMakePresets.json
The applications were not built in the correct path, because APP_NAME was not used because it was not in the inheritance chain anymore.
Fixes: 09e98103bf7da8b8a3f2007e86ba5dbc58a45a0b
> fix sample application cmake prefix

- images/arm64/nxp/rdb2/kernel_src/Makefile
Fix build-dep getting stuck when non interactive. Solves issue #70. 
none
```bash
```
> Fix build-dep getting stuck when non interactive

- docs/intro/arm64_host.md
Fixes example paths in documentation as the original paths did not exist.
```bash
```
> Fix non-existing paths in documentation

- .devcontainer/devcontainer.json
- images/arm64/beaglebone/ai64/beaglebone.mk
- robot_tests/images.robot
- Update dev container to v1.4.11.
none
```bash
(venv) ebcl@2fa57ecceb65:/workspace/robot_tests$ robot images.robot 
==============================================================================
Images                                                                        
==============================================================================
Build Image amd64/qemu/jammy                                          | PASS |
------------------------------------------------------------------------------
Build Image amd64/qemu/ebcl/systemd                                   | PASS |
------------------------------------------------------------------------------
Build Image amd64/qemu/ebcl/crinit                                    | PASS | …
```
> Update dev container to v1.4.11 for 1.x line

- .devcontainer/devcontainer.json
- images/arm64/beaglebone/ai64/beaglebone.mk
- images/arm64/beaglebone/ai64/boot_configure.sh
- robot_tests/images.robot
- Fix BB AI64 image build
- Fix BB AI64 robot tests
Tested with EBcL build tools v1.4.11.
```bash
(venv) ebcl@2fa57ecceb65:/workspace/robot_tests$ robot -i ai64 images.robot 
==============================================================================
Images                                                                        
==============================================================================
Build Image arm64/beaglebone/ai64/crinit                              | PASS |
------------------------------------------------------------------------------
Build Image arm64/beaglebone/ai64/systemd                             | PASS |
------------------------------------------------------------------------------
Images                                                                | …
```
> Fix bb ai64 image

- .github/workflows/robot-tests.yml
As documented in the docs / setup. There is a bug on qemu-user-static in ubuntu 24.04. This leads to failures on arm64 builds.
Change main test workflow to ubuntu-22.04
no
see checks.
> Switch main_1.x tests to ubuntu-22.04

- apps/ebclfsa-demo/hi/hi_main.c
ebclfsa-demo:
Utilize the CMake JSON configuration file to build the demo application with musl libraries, the Clang compiler, and the LLD linker.
ebclfsa-demo: 
The Clang compiler is stricter than GCC and raises errors for non-compliant source code. To successfully build the project, the source code of ebclfsa was slightly modified.
> Build ebclfsa with clang and musl

- .github/workflows/robot-tests.yml
The automated robots tests are currently only working on ubuntu-22.04, and ubuntu-latest is a moving target (and 24.04 now).
In any case a versioned ubuntu version should be used for testing.
Tests for arm are failing due to the qemu-user-static version included in ubuntu-24.04.
This change fixes the runners to ubuntu-22.04 for now.
n/a
see checks
> Pin robot test workflows to ubuntu-22.04

- apps/ebclfsa-demo/hi/hi_main.c
The Clang compiler is stricter than GCC and raises warnings for non-compliant source code. To successfully build the project, the source code of ebclfsa was slightly modified.
(cherry picked from commit 744be70bbf83c149f25f331ed3c7cfaf6f8bd33a)
>  [sync from main_1.x] ebclfsa-demo: adjust code for Clang compiler

- init_workspace
When starting the template in a github codespace, the packages checked in init_workspace prevent that.
This change adds automatic installation of those packages, when in a CODESPACE environment.
n/a
n/a
> add support for codespaces: install packages

- docs/intro/setup.md
- init_container
It is not unlikely that a user has images/apps in more then one git repo, so clone all repos in the comma separated env vars.
```bash
not needed here
```
>  EBcL SDK setup customization clone multiple app/images

- init_workspace
Use which to be independent of installed location of qemu-aarch64-static as this was an issue on WSL noble combinations
na
> QEMU binfmt support check independent of location

- ebcl_sdk.code-workspace
When working with qemu and especially the hypervisor in the terminal, key sequences like CTRL+E are required. Most sequences have keybinds in vscode, that are interpreted even in a terminal.
This option disables the keybinds, while the focus is in the terminal, so these sequences can be sent to the terminal
(cherry picked from commit 12b60416d1ee0bd5b787ca9c8c73193afbd2d890)
> vscode: disable keybinds in terminal

- ebcl_sdk.code-workspace
Starting bash with the -l parameter starts it in interactive shell mode, which sources /etc/profile. This is required to load for example bash-completions, when they are installed.
This only makes a real difference after Elektrobit/ebcl_dev_container#56 is merged and integrated into the workspace.
With these two changes full bash completion is working (i.e. git checkout <TAB> or task <TAB>)
> vscode: make terminal default to interactive shell
