Elektrobit/ebcl_template

.github/workflows/vscode-tasks.yml
init_container

Adding a simple CI that performs and end to end test: checkout, enter devcontainer, run a VScode task to build and QEMU image.
Had to fix the init_container command, which may break things for other contexts, please review.
Issue: devcontainer is started as ebcl user, but the path modifications need root, at least in the context of github.com actions.
n/a
See action results, e.g. over here https://github.com/antonjahn/ebcl_template/actions/runs/11444477939

Proof-of-Concept: Minimal CI > Feedback wanted

---

.github/workflows/vscode-tasks.yml

_(Provide a brief description of the changes in this pull request)_
```bash
```

cache the devcontainer on ghcr

---

.github/workflows/vscode-tasks.yml

As observed in #33 there are build issues with berrymill jobs. To fix this they are dropped with this change.
see checks.

remove berrymill jobs from vscode-tasks.yml

---

.github/workflows/pdf.yml

Do not use name as this would just rename the built pdf
```bash
```
- N/A Grammar: the content is grammatically correct
- N/A Comprehensibility/Unambiguousness: the content is easy readable, clear to understand
- N/A Correctness and consistency: the content is technically correct and consistent,
- N/A Terminology: technical terms are clear and they are used correctly and documented in the glossary
- N/A Level of detail: the content matches the detail level necessary for the reviewed object
- N/A Grammar: the content is grammatically correct
- N/A Comprehensibility/Unambiguousness: the content is easy readable, clear to understand
- N/A …

docs: fix pdf build

---

images/arm64/qemu/ebcl/crinit/README.md
images/arm64/qemu/ebcl/crinit/image.raw
images/arm64/qemu/ebcl/crinit/vmlinuz

- Update readme with new path.
- Add symlinks for run script.
None
N/A
- N/A Issue: If a related GitHub issue exists, linking is done

Update prebuilt qemu arm64 image

---

init_workspace

Merge missing commit from main into main_1.x

Quality of life: Ensure required tools are installed on host (#61)

---

.github/workflows/mdbook.yml
.github/workflows/robot-tests.yml

_(Provide a brief description of the changes in this pull request)_
```bash
```

Update Workflows to Trigger on main* branches

---

docs/examples/qemu_ebclfsa.md
images/arm64/qemu/ebclfsa/Makefile
images/arm64/qemu/ebclfsa/Readme.dist

- Fix some issues in parallel build and remove parallel build from the recommendation in the documentation because there are some issues with the cache.
- Add dist target to create an archive with the image, uboot and a run_qemu script

Update for ebclfsa image

---

images/amd64/appdev/qemu/crinit/root.yaml
images/amd64/qemu/ebcl-server/crinit/root.yaml
images/arm64/appdev/pi4/crinit/root.yaml
images/arm64/appdev/qemu/crinit/root.yaml
images/arm64/appdev/rdb2/crinit/root.yaml
images/arm64/nxp/rdb2/network/root.yaml
images/arm64/raspberry/pi4/crinit/root.yaml

Package now has all dependencies listed, no need to include manually any more
na
```bash
```
- N/A Grammar: the content is grammatically correct
- N/A Comprehensibility/Unambiguousness: the content is easy readable, clear to understand
- N/A Correctness and consistency: the content is technically correct and consistent,
- N/A Terminology: technical terms are clear and they are used correctly and documented in the glossary
- N/A Level of detail: the content matches the detail level necessary for the reviewed object
- N/A Grammar: the content is grammatically correct
- N/A Comprehensibility/Unambiguousness: the content is easy readable, clear to …

elos: remove manual dependencies

---

.devcontainer/devcontainer.json
.gitignore
images/amd64/qemu/grub-efi/Taskfile.yml
images/amd64/qemu/grub-efi/base.yaml
images/amd64/qemu/grub-efi/config/etc/crinit/crinit.d/agetty-ttyS0.crinit
images/amd64/qemu/grub-efi/config/etc/crinit/crinit.d/earlysetup.crinit
images/amd64/qemu/grub-efi/config/etc/crinit/crinit.d/mount.crinit
images/amd64/qemu/grub-efi/config/etc/crinit/default.series
images/amd64/qemu/grub-efi/config/sbin/init
images/amd64/qemu/grub-efi/config_root.sh
images/amd64/qemu/grub-efi/efi.yml
images/amd64/qemu/grub-efi/grub.cfg
images/amd64/qemu/grub-efi/image.yaml
images/amd64/qemu/grub-efi/initrd.yaml
images/amd64/qemu/grub-efi/root.yaml
images/amd64/qemu/grub-efi/tasks/Efi.yml
images/amd64/qemu/grub-efi/tasks/Embdgen.yml
images/amd64/qemu/grub-efi/tasks/Generic.yml
images/amd64/qemu/grub-efi/tasks/InitrdGenerator.yml
images/amd64/qemu/grub-efi/tasks/Qemu.yml
images/amd64/qemu/grub-efi/tasks/RootGenerator.yml
images/qemu.yml
images/qemu_x86_64_efi.yml

- Add a amd64 example image which makes use of grub-efi.
none
```bash
```
- N/A Issue: If a related GitHub issue exists, linking is done

Grub efi amd64 image

---

apps/my-qt-app/CMakeLists.txt
apps/my-qt-app/CMakePresets.json
apps/my-qt-app/helloworld.cpp
ebcl_sdk.code-workspace
images/amd64/appdev/qemu/base.yaml
images/amd64/appdev/qemu/initrd.yaml
images/amd64/appdev/qemu/root_common.yaml

Add qt app for qemu amd64 system image usage
```bash
```

Add a qt app for qemu amd64 systemd image

---

init_workspace

Reverts Elektrobit/ebcl_template#76

Revert "Quality of life: Ensure required tools are installed on host (#61)"

---

docs/SUMMARY.md
docs/examples/qemu_xen.md
images/amd64/qemu/xen/Makefile
images/amd64/qemu/xen/dom0/base.yaml
images/amd64/qemu/xen/dom0/systemd/config_grub.sh
images/amd64/qemu/xen/dom0/systemd/config_root.sh
images/amd64/qemu/xen/dom0/systemd/domu/opt/images/.gitignore
images/amd64/qemu/xen/dom0/systemd/grub_config/etc/default/grub
images/amd64/qemu/xen/dom0/systemd/root.yaml
images/amd64/qemu/xen/dom0/systemd/systemd_config/etc/systemd/system/start-ebcl-1.service
images/amd64/qemu/xen/dom0/systemd/xen_config/etc/xen/ebcl.cfg
images/amd64/qemu/xen/dom0_image.yaml
images/amd64/qemu/xen/domu/base.yaml
images/amd64/qemu/xen/domu/boot.yaml
images/amd64/qemu/xen/domu/boot_root.yaml
images/amd64/qemu/xen/domu/config_boot.sh
images/amd64/qemu/xen/domu/crinit/config_root.sh
images/amd64/qemu/xen/domu/crinit/crinit_config/etc/crinit/crinit.d/agetty-hvc0.crinit
images/amd64/qemu/xen/domu/crinit/crinit_config/etc/crinit/crinit.d/earlysetup.crinit
images/amd64/qemu/xen/domu/crinit/crinit_config/etc/crinit/crinit.d/mount.crinit
images/amd64/qemu/xen/domu/crinit/crinit_config/etc/crinit/default.series
images/amd64/qemu/xen/domu/crinit/crinit_config/sbin/init
images/amd64/qemu/xen/domu/crinit/pvgrub_config/grub/grub.cfg
images/amd64/qemu/xen/domu/crinit/root.yaml
images/amd64/qemu/xen/domu_image.yaml

Add  initial Xen PoC images:
- xen/dom0 systemd image providing systemd, udev, grub-efi and xen hypervisor.
- xen/domu crinit image.
The guest image (domu) is included in the host rootfs (/opt/images/domu.img) and the guest is started by a systemd service.
Grub is configured to the EFI partition as a separate step (see dom0/systemd/config_grub.sh) after the image is build. 
pvgrub doesn't seem to understand recent zstd compressed kernels. Using such will produce "error: not xen image". This is resolved by uncompressing the kernel with "extract-vmlinux" scripts which comes with kernel source package (see domu/config_boot.sh).
TODO:
- Networking
```bash
```
no …

images: add initial Xen images

---

init_workspace

Previously we only checked if the `.ssh` directory existed, also check if the directory is not empty before copying it's content.
_(Provide a brief description of the changes in this pull request)_
```bash
```

Fix SSH key copying in init_workspace

---

.env
docs/examples/rdb2.md
docs/images/from_scatch.md
images/amd64/appdev/qemu/crinit/config/etc/apt/sources.list
images/amd64/qemu/ebcl-server/crinit/config/etc/apt/sources.list
images/arm64/appdev/pi4/crinit/crinit_config/etc/apt/sources.list
images/arm64/appdev/pi4/systemd/systemd_config/etc/apt/sources.list
images/arm64/appdev/qemu/crinit/config/etc/apt/sources.list
images/arm64/appdev/rdb2/base.yaml
images/arm64/appdev/rdb2/systemd/systemd_config/etc/apt/sources.list
images/arm64/nxp/rdb2/base.yaml
images/arm64/nxp/rdb2/systemd/server/config/etc/apt/sources.list
images/arm64/qemu/ebclfsa/base.yaml
images/arm64/raspberry/pi4/crinit/crinit_config/etc/apt/sources.list
images/arm64/raspberry/pi4/systemd/systemd_config/etc/apt/sources.list
images/example-old-images/qemu/berrymill/berrymill.conf
images/example-old-images/qemu/berrymill/root/etc/apt/sources.list

Update http to https on linux.elektrobit.com mentions
N/A
```bash
```

Update http to https on linux.elektrobit.com mentions

---

.vscode/extensions.json

Recommend to install dev container when opening ws
na
na
- na Test: Changes are tested
- na Doc: Documentation has been updated 
- na Issue: If a related GitHub issue exists, linking is done
- na Review: Tested by the reviewer

Add settings to ensure dev container extension is recommeded

---

book.toml
docs/intro/arm64_host.md
docs/intro/setup.md

Testers have found more issues with the docs and Running on ubuntu 24.04.
It's very easy to get in a broken state, due to automatic updates.
no
see checks

Extend workaround description for Ubuntu 24.04

---

.github/workflows/mdbook.yml
.github/workflows/robot-tests.yml
apps/meminfo-reader/CMakePresets.json
apps/my-json-app/CMakePresets.json
apps/my-qt-app/CMakePresets.json
docs/images/from_scatch.md
images/amd64/qemu/ebcl/crinit/config_root.sh
images/amd64/qemu/grub-efi/config_root.sh
images/arm64/nxp/rdb2/crinit/config_root.sh
images/tasks/Kernel.yml
init_workspace

- Port all outstanding changes after branch out
```bash
Enforced image rebuild is off...
Robot Framework 7.2 (Python 3.10.12 on linux)
PYTHONPATH: /workspace/robot_tests/lib:
==============================================================================
Images & Qemu Performance                                                     
==============================================================================
Images & Qemu Performance.Images                                              
==============================================================================
[ WARN ] SDK_ROBOT_SKIP_CLEAN is 1, skipping image rebuild.                   
Build Image amd64/qemu/jammy                                          | PASS |
------------------------------------------------------------------------ …
```

Porting 2.0 updates

---

.devcontainer/devcontainer.json
images/arm64/qemu/ebclfsa/Makefile
images/arm64/qemu/ebclfsa/tools_extract.yaml

Use the new feature of the hypervisor config tool, to download the specialization package.

[main_1.x] ebclfsa: use hypervisor specialization package feature and update container to 1.4.13

---

.devcontainer/devcontainer.json
images/arm64/qemu/ebclfsa/Taskfile.hv.yaml
images/arm64/qemu/ebclfsa/Taskfile.tools.yaml
images/arm64/qemu/ebclfsa/Taskfile.yml

Use the new feature of the hypervisor config tool, to download the specialization package.

[main_2.x] ebclfsa: use hypervisor specialization package feature and update container to 1.4.13

---

.github/workflows/mdbook.yml
book.toml

Extend the mdbook workflow to build multiple versions of the documentation, from a list of branches.
Each branch is built individually, and all are then published to /branch_name url.
The main "page" is just a redirect to a hard coded branch.
With this PR the hard-coded redirect target is main_2.x branch.
When switching the default branch, this would need to be adjusted.
The workflow should be maintained on the main branch, and will be triggered by all active main_* branches.
Merging this PR will break incoming links to unversioned docs.
The redirection only works for the index / top page.
n/a
robot tests are not affected and not run manually.
deployment has been tested on a fork.
(spelling, …

build versioned docs

---

docs/intro/setup.md

- clarify the version of qemu that will work
- fix typos

Documentation Improvement Ideas

---

.devcontainer/devcontainer.json
.env
docs/examples/kernel.md
docs/examples/rdb2.md
docs/images/from_scatch.md
images/amd64/appdev/qemu/crinit/config/etc/apt/sources.list
images/arm64/appdev/rdb2/base.yaml
images/arm64/appdev/rdb2/boot_root.yaml
images/arm64/nxp/rdb2/base.yaml
images/arm64/nxp/rdb2/boot_root.yaml
images/arm64/nxp/rdb2/kernel_src/Makefile
images/arm64/qemu/ebclfsa/base.yaml
images/example-old-images/qemu/berrymill/berrymill.conf

_(Provide a brief description of the changes in this pull request)_
```bash
```

EBcL release 1.5

---

docs/SUMMARY.md
docs/intro/dev_container.md
docs/intro/setup.md
images/tasks/Sysroot.yml

- Add notes on how to use devcontainer-cli for development without vscode UI
none
not needed here

docs: devcontainer-cli

---

docs/images/params.md

docs: Precendence of host_files
